# Generated by Django 6.0.8 on 2026-08-05 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='equipo_descripcion',
            field=models.CharField(blank=True, help_text='Ej. iPhone 12, Laptop Dell Inspiron', max_length=200),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='servicio_tipo',
            field=models.CharField(blank=True, choices=[('MANTENIMIENTO', 'Mantenimiento'), ('DIAGNOSTICO', 'Diagnóstico'), ('REPARACION', 'Reparación')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='tipo',
            field=models.CharField(choices=[('PRODUCTO', 'Producto'), ('SERVICIO', 'Servicio')], default='PRODUCTO', max_length=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.producto'),
        ),
    ]
