# Generated by Django 6.0.8 on 2026-08-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_detallefactura_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='accesorios',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='adelanto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='categoria_equipo',
            field=models.CharField(blank=True, choices=[('COMPUTADORA', 'Computadora'), ('CELULAR', 'Celular'), ('TABLET', 'Tablet'), ('OTRO', 'Otro')], max_length=20),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='checklist_entrada',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='como_supo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='contrasena_equipo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='especificaciones',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='modelo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='no_serie',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
