# Generated by Django 6.0.8 on 2026-08-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_cliente_empresa_detallefactura_accesorios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólares (US$)'), ('NIO', 'Córdobas (C$)')], default='USD', max_length=3),
        ),
    ]
