# Generated by Django 6.0.8 on 2026-08-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_detallefactura_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(blank=True, max_length=30, verbose_name='Cédula / ID'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_entrega',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='operadora',
            field=models.CharField(blank=True, choices=[('CLARO', 'Claro'), ('MOVISTAR', 'Movistar')], max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(blank=True, max_length=30, verbose_name='RUC'),
        ),
    ]
