# Generated by Django 6.0.8 on 2026-08-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_cliente_cedula_cliente_direccion_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólares (US$)'), ('NIO', 'Córdobas (C$)')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='factura',
            name='tasa_cambio_aplicada',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=8),
        ),
        migrations.AddField(
            model_name='factura',
            name='total_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
