# Generated by Django 6.0.8 on 2026-08-18 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto aplicado a la factura, en la moneda de la factura', max_digits=12)),
                ('monto_recibido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.factura')),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
    ]
