# Generated by Django 6.0.8 on 2026-08-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_alter_detallefactura_cantidad_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='contacto_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='empresa',
            name='contacto_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='empresa',
            name='contacto_puesto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='contacto_telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='operadora',
            field=models.CharField(blank=True, choices=[('CLARO', 'Claro'), ('TIGO', 'Tigo')], max_length=10),
        ),
    ]
