# Generated by Django 6.0.8 on 2026-08-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_empresa_contacto_email_empresa_contacto_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefono2',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono alterno'),
        ),
    ]
