# Generated by Django 6.0.8 on 2026-08-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_cliente_telefono2'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='banco',
            field=models.CharField(blank=True, help_text='Banco o financiera, si aplica', max_length=100),
        ),
        migrations.AddField(
            model_name='pago',
            name='cuotas',
            field=models.PositiveIntegerField(blank=True, help_text='Número de cuotas, si aplica', null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='referencia',
            field=models.CharField(blank=True, help_text='N.º de autorización, referencia o últimos dígitos', max_length=100),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('CREDEX', 'Credex'), ('TASA_CERO', 'Tasa Cero'), ('LINEA_CREDITO', 'Línea de Crédito')], max_length=20),
        ),
    ]
