# Generated by Django 6.0.8 on 2026-08-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_pago_banco_pago_cuotas_pago_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='departamento_pais',
            field=models.CharField(blank=True, max_length=100, verbose_name='Departamento / País'),
        ),
    ]
