# Generated by Django 6.0.8 on 2026-09-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_cliente_departamento_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='es_problematico',
            field=models.BooleanField(default=False, verbose_name='Cliente problemático'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='motivo_problematico',
            field=models.TextField(blank=True, verbose_name='Motivo'),
        ),
    ]
