# Generated by Django 6.0.8 on 2026-09-03 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArqueoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del cierre')),
                ('caja_chica_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Caja chica inicial (efectivo)')),
                ('pagos_cheque_cierre', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Pagos con cheque (cierre)')),
                ('pagos_transferencia_cierre', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Pagos en transferencia (cierre)')),
                ('compras_credex_cierre', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Compras con CREDEX (cierre)')),
                ('cierre_pos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cierre en POS')),
                ('creditos_cierre', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Créditos (cierre)')),
                ('creditos', models.JSONField(blank=True, default=list)),
                ('ingresos_ventas', models.JSONField(blank=True, default=list)),
                ('gastos_caja_chica', models.JSONField(blank=True, default=list)),
                ('recibos_caja_utilizados', models.CharField(blank=True, max_length=255, verbose_name='Recibos de caja utilizados')),
                ('comentarios', models.TextField(blank=True)),
                ('ventas_dia_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_com_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cca_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('repuestos_uso_interno_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rep_acc_insumo_externa_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Repuestos/accesorios/insumos venta externa (anterior)')),
                ('computadoras_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ventas_por_vendedor', models.JSONField(blank=True, default=list)),
                ('meta_semanal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('meta_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('equipos_por_vendedor', models.JSONField(blank=True, default=list)),
                ('dia_del_mes', models.PositiveIntegerField(default=1)),
                ('dias_mes', models.PositiveIntegerField(default=30)),
                ('tipo_cambio', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('billetes_usd_100', models.PositiveIntegerField(default=0)),
                ('billetes_usd_50', models.PositiveIntegerField(default=0)),
                ('billetes_usd_20', models.PositiveIntegerField(default=0)),
                ('billetes_usd_10', models.PositiveIntegerField(default=0)),
                ('billetes_usd_5', models.PositiveIntegerField(default=0)),
                ('billetes_usd_1', models.PositiveIntegerField(default=0)),
                ('billetes_nio_1000', models.PositiveIntegerField(default=0)),
                ('billetes_nio_500', models.PositiveIntegerField(default=0)),
                ('billetes_nio_200', models.PositiveIntegerField(default=0)),
                ('billetes_nio_100', models.PositiveIntegerField(default=0)),
                ('billetes_nio_50', models.PositiveIntegerField(default=0)),
                ('billetes_nio_20', models.PositiveIntegerField(default=0)),
                ('billetes_nio_10', models.PositiveIntegerField(default=0)),
                ('billetes_nio_5', models.PositiveIntegerField(default=0)),
                ('billetes_nio_1', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arqueos_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arqueo de caja',
                'verbose_name_plural': 'Arqueos de caja',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
