# Generated by Django 6.0.8 on 2026-09-03 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arqueocaja',
            name='cerrada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='cerrada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arqueos_cerrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10),
        ),
        migrations.AlterField(
            model_name='arqueocaja',
            name='fecha',
            field=models.DateField(unique=True, verbose_name='Fecha del cierre'),
        ),
    ]
