# Generated by Django 6.0.8 on 2026-09-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0002_arqueocaja_cerrada_en_arqueocaja_cerrada_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqueocaja',
            name='caja_chica_inicial_cordobas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Caja chica inicial (córdobas)'),
        ),
        migrations.AlterField(
            model_name='arqueocaja',
            name='caja_chica_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Caja chica inicial (dólares)'),
        ),
    ]
