# Generated by Django 6.0.8 on 2026-08-05 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('rrhh', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('equipo', models.CharField(help_text='Ej. Laptop HP Pavilion 14', max_length=200)),
                ('problema_reportado', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_REPARACION', 'En reparación'), ('LISTO_ENTREGA', 'Listo para entrega'), ('ENTREGADO', 'Entregado')], default='RECIBIDO', max_length=20)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_taller', to='ventas.cliente')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_taller', to='rrhh.empleado')),
            ],
            options={
                'ordering': ['-fecha_ingreso', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InsumoUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='taller.ordentaller')),
            ],
        ),
    ]
