# Generated by Django 6.0.8 on 2026-08-05 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentaller',
            name='fecha_entrega_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='origen_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_generada', to='ventas.detallefactura'),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='tipo_servicio',
            field=models.CharField(blank=True, choices=[('MANTENIMIENTO', 'Mantenimiento'), ('DIAGNOSTICO', 'Diagnóstico'), ('REPARACION', 'Reparación')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordentaller',
            name='equipo',
            field=models.CharField(help_text='Ej. Laptop HP Pavilion 14 / iPhone 12', max_length=200),
        ),
    ]
