# Generated by Django 6.0.8 on 2026-08-05 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_ordentaller_fecha_entrega_real_and_more'),
        ('ventas', '0002_detallefactura_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentaller',
            name='origen_venta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_generada', to='ventas.detallefactura'),
        ),
    ]
