# Generated by Django 6.0.8 on 2026-08-06 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_alter_ordentaller_origen_venta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentaller',
            name='accesorios',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='adelanto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='categoria_equipo',
            field=models.CharField(choices=[('COMPUTADORA', 'Computadora'), ('CELULAR', 'Celular'), ('TABLET', 'Tablet'), ('OTRO', 'Otro')], default='COMPUTADORA', max_length=20),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='checklist_entrada',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='checklist_salida',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='como_supo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='contrasena_equipo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='especificaciones',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='modelo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='no_serie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_vendidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
