# Generated by Django 6.0.8 on 2026-08-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0004_ordentaller_accesorios_ordentaller_adelanto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentaller',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólares (US$)'), ('NIO', 'Córdobas (C$)')], default='USD', max_length=3),
        ),
    ]
