# Generated by Django 6.0.8 on 2026-08-06 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0005_ordentaller_moneda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentaller',
            name='aceptacion_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='bateria_original',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='camara_funciona',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='capacidad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='comentarios',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='danos_visibles',
            field=models.JSONField(blank=True, default=list, help_text='Puntos marcados sobre el diagrama del equipo'),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='diagnostico',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='encendido',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='estado_equipo_notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='estado_general',
            field=models.CharField(blank=True, choices=[('BUENO', 'Bueno'), ('MALO', 'Malo'), ('REGULAR', 'Regular')], max_length=10),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='firma_cliente',
            field=models.TextField(blank=True, help_text='Imagen de firma en base64'),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='firma_tecnico',
            field=models.TextField(blank=True, help_text='Imagen de firma en base64'),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('CREDITO', 'Crédito'), ('CONTADO', 'Contado')], max_length=10),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='imei1',
            field=models.CharField(blank=True, max_length=30, verbose_name='IMEI 1'),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='imei2',
            field=models.CharField(blank=True, max_length=30, verbose_name='IMEI 2'),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='impuestos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='necesita_repuestos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='numero_chip',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='operadora_equipo',
            field=models.CharField(blank=True, choices=[('CLARO', 'Claro'), ('MOVISTAR', 'Movistar')], max_length=10),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='patron_desbloqueo',
            field=models.JSONField(blank=True, default=list, help_text='Secuencia de puntos 0-8'),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='recibe',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='recomendaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='repuestos',
            field=models.JSONField(blank=True, default=list, help_text='[{descripcion, tipo, precio}]'),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='servicios_realizados',
            field=models.JSONField(blank=True, default=list, help_text='[{descripcion, precio}]'),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='sistema_operativo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='tipos_servicio',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='tipos_servicio_otro',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ordentaller',
            name='estado',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('DIAGNOSTICO', 'Diagnóstico'), ('EN_REPARACION', 'En reparación'), ('ESPERANDO_REPUESTO', 'Esperando repuesto'), ('LISTO_ENTREGA', 'Listo para entregar'), ('ENTREGADO', 'Entregado')], default='RECIBIDO', max_length=20),
        ),
        migrations.CreateModel(
            name='FotoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='ordenes/fotos/')),
                ('momento', models.CharField(choices=[('RECEPCION', 'Recepción'), ('ENTREGA', 'Entrega')], default='RECEPCION', max_length=10)),
                ('subida_en', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='taller.ordentaller')),
            ],
            options={
                'ordering': ['-subida_en'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='taller.ordentaller')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
