# Generated by Django 6.0.8 on 2026-08-08 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
        ('taller', '0006_ordentaller_aceptacion_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialestado',
            name='estado_anterior',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_nuevo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ordentaller',
            name='estado',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('DIAGNOSTICO', 'Diagnóstico'), ('ESPERANDO_AUTORIZACION', 'Esperando autorización'), ('EN_REPARACION', 'En reparación'), ('ESPERANDO_REPUESTO', 'Esperando repuesto'), ('LISTO_ENTREGA', 'Listo para entregar'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado'), ('REINGRESO', 'Reingreso')], default='RECIBIDO', max_length=30),
        ),
        migrations.CreateModel(
            name='DetalleComputadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipo', models.CharField(choices=[('LAPTOP', 'Laptop'), ('PC_ESCRITORIO', 'PC de escritorio'), ('ALL_IN_ONE', 'All-in-One'), ('MACBOOK', 'MacBook'), ('MINI_PC', 'Mini PC'), ('SERVIDOR', 'Servidor'), ('MONITOR', 'Monitor'), ('OTRO', 'Otro')], default='LAPTOP', max_length=20)),
                ('procesador_generacion', models.CharField(blank=True, max_length=150)),
                ('estado_fisico', models.JSONField(blank=True, default=dict)),
                ('ram_tipo', models.CharField(blank=True, max_length=50)),
                ('ram_frecuencia', models.CharField(blank=True, max_length=50)),
                ('ram_slots', models.CharField(blank=True, max_length=50)),
                ('disco_capacidad', models.CharField(blank=True, max_length=50)),
                ('tipo_almacenamiento', models.CharField(blank=True, choices=[('HDD', 'HDD'), ('SSD', 'SSD'), ('NVME', 'NVMe')], max_length=10)),
                ('marca_disco', models.CharField(blank=True, max_length=100)),
                ('serial_disco', models.CharField(blank=True, max_length=100)),
                ('tipo_conector', models.CharField(blank=True, choices=[('SATA', 'SATA'), ('NVME', 'NVMe'), ('OTRO', 'Otro')], max_length=10)),
                ('componentes', models.JSONField(blank=True, default=dict)),
                ('accesorios_detalle', models.JSONField(blank=True, default=list)),
                ('sin_contrasena', models.BooleanField(default=False)),
                ('empresa_controla_software', models.BooleanField(blank=True, null=True)),
                ('primera_vez', models.BooleanField(blank=True, null=True)),
                ('bitlocker_activo', models.BooleanField(blank=True, null=True)),
                ('bitlocker_clave', models.CharField(blank=True, max_length=255, verbose_name='Clave de recuperación BitLocker')),
                ('software', models.JSONField(blank=True, default=dict)),
                ('checklist_entrada', models.JSONField(blank=True, default=dict)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_com', to='taller.ordentaller')),
                ('tecnico_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_com_entregados', to='rrhh.empleado')),
                ('tecnico_recibe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_com_recibidos', to='rrhh.empleado')),
            ],
        ),
    ]
