# Generated by Django 6.0.8 on 2026-08-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0008_ordentaller_equipo_vinculado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentaller',
            name='firma_cliente_entrega',
            field=models.TextField(blank=True, help_text='Firma del cliente al retirar el equipo (Recibí conforme) — imagen base64'),
        ),
        migrations.AlterField(
            model_name='ordentaller',
            name='estado_general',
            field=models.CharField(blank=True, choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('ENCIENDE_CON_FALLA', 'Enciende con falla')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ordentaller',
            name='firma_cliente',
            field=models.TextField(blank=True, help_text='Firma del cliente al recibir el equipo (Leí y entendí) — imagen base64'),
        ),
    ]
