# Generated by Django 6.0.8 on 2026-08-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0009_ordentaller_firma_cliente_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentaller',
            name='estado',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('DIAGNOSTICO', 'Diagnóstico'), ('ESPERANDO_AUTORIZACION', 'Esperando autorización'), ('EN_REPARACION', 'En reparación'), ('ESPERANDO_REPUESTO', 'Esperando repuesto'), ('LISTO_ENTREGA', 'Listo para entregar'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado'), ('REINGRESO', 'Reingreso'), ('ABANDONADO', 'Abandonado')], default='RECIBIDO', max_length=30),
        ),
    ]
