# Generated by Django 6.0.8 on 2026-08-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0010_alter_ordentaller_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecomputadora',
            name='sin_contrasena',
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='sin_contrasena',
            field=models.BooleanField(default=False, help_text='El cliente no proporciona la contraseña del equipo'),
        ),
        migrations.AlterField(
            model_name='ordentaller',
            name='encendido',
            field=models.CharField(blank=True, choices=[('ENCIENDE_OK', 'Enciende OK'), ('ENCIENDE_CON_FALLA', 'Enciende con falla'), ('ENCIENDE_SIN_IMAGEN', 'Enciende pero sin imagen'), ('NO_ENCIENDE', 'No enciende')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordentaller',
            name='operadora_equipo',
            field=models.CharField(blank=True, choices=[('CLARO', 'Claro'), ('TIGO', 'Tigo')], max_length=10),
        ),
    ]
