# Generated by Django 6.0.8 on 2026-08-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0011_remove_detallecomputadora_sin_contrasena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoequipo',
            name='momento',
            field=models.CharField(choices=[('RECEPCION', 'Recepción'), ('DIAGNOSTICO', 'Diagnóstico'), ('ENTREGA', 'Entrega')], default='RECEPCION', max_length=11),
        ),
    ]
