# Generated by Django 6.0.8 on 2026-08-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0012_alter_fotoequipo_momento'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecomputadora',
            name='respaldo_solicitado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='fecha_hora_recepcion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='repuesto_inmediato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='tiempo_reparacion_estimado',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
