# Generated by Django 6.0.8 on 2026-08-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0013_detallecomputadora_respaldo_solicitado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecomputadora',
            name='comprado_nuevo',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
