# Generated by Django 6.0.8 on 2026-08-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0014_detallecomputadora_comprado_nuevo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentaller',
            name='equipo_apagado_recepcion',
            field=models.BooleanField(default=False),
        ),
    ]
