# Generated by Django 6.0.8 on 2026-08-24 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0004_permisoempleado_horarioempleado'),
        ('taller', '0015_ordentaller_equipo_apagado_recepcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentaller',
            name='asesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_como_asesor', to='rrhh.empleado'),
        ),
    ]
