# Generated by Django 6.0.8 on 2026-08-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0016_ordentaller_asesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentaller',
            name='numero',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
