# Generated by Django 6.0.8 on 2026-08-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0017_alter_ordentaller_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentaller',
            name='fecha_hora_entrega_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
