# Generated by Django 6.0.8 on 2026-08-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0018_ordentaller_fecha_hora_entrega_real'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentaller',
            name='estado',
            field=models.CharField(choices=[('RECIBIDO', 'Por empezar'), ('DIAGNOSTICO', 'Diagnóstico'), ('ESPERANDO_AUTORIZACION', 'Esperando autorización'), ('EN_REPARACION', 'En Proceso'), ('ESPERANDO_REPUESTO', 'Esperando repuesto'), ('IMPORTACION', 'Importación'), ('LISTO_ENTREGA', 'Equipo listo'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado'), ('REINGRESO', 'Reingreso'), ('ABANDONADO', 'Abandonado')], default='RECIBIDO', max_length=30),
        ),
    ]
