# Generated by Django 6.0.8 on 2026-08-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0020_alter_ordentaller_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentaller',
            name='repuestos_extraidos_abandono',
            field=models.TextField(blank=True),
        ),
    ]
