# Generated by Django 6.0.8 on 2026-08-28 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0008_uniformedia_empleado_uniforme_asignado_and_more'),
        ('taller', '0021_ordentaller_repuestos_extraidos_abandono'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='taller.ordentaller')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.empleado')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='fotoequipo',
            name='diagnostico_orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='taller.diagnosticoorden'),
        ),
    ]
