# Generated by Django 6.0.8 on 2026-09-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0022_diagnosticoorden_fotoequipo_diagnostico_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecomputadora',
            name='trae_receptor_mouse',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='instrucciones_asesor',
            field=models.TextField(blank=True, verbose_name='Detalles del servicio'),
        ),
    ]
