# Generated by Django 6.0.8 on 2026-09-16 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0023_detallecomputadora_trae_receptor_mouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentaller',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
