# Generated by Django 6.0.8 on 2026-08-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=30, unique=True, verbose_name='Cédula')),
                ('puesto', models.CharField(max_length=100)),
                ('area', models.CharField(choices=[('TALLER', 'Taller'), ('VENTAS', 'Ventas'), ('RRHH', 'Recursos Humanos'), ('BACKOFFICE', 'Backoffice / Contabilidad'), ('ADMIN', 'Gerencia General')], default='BACKOFFICE', max_length=20)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('fecha_ingreso', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('equipos_asignados', models.ManyToManyField(blank=True, related_name='empleados_asignados', to='inventario.producto')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
