# Generated by Django 6.0.8 on 2026-08-08 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='avatar_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='empleados/fotos/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='area',
            field=models.CharField(choices=[('TALLER', 'Taller'), ('PASANTE', 'Pasante de taller'), ('VENTAS', 'Ventas'), ('RRHH', 'Recursos Humanos'), ('BACKOFFICE', 'Backoffice / Contabilidad'), ('ADMIN', 'Gerencia General')], default='BACKOFFICE', max_length=20),
        ),
        migrations.CreateModel(
            name='RegistroHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_horas', to='rrhh.empleado')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
