# Generated by Django 6.0.8 on 2026-08-19 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_empleado_avatar_color_empleado_foto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='area',
            field=models.CharField(choices=[('TALLER', 'Taller'), ('PASANTE', 'Pasante de taller'), ('VENTAS', 'Ventas'), ('RRHH', 'Recursos Humanos'), ('BACKOFFICE', 'Backoffice / Contabilidad'), ('JEFE_OPERACIONES', 'Jefe de Operaciones'), ('ADMIN', 'Gerencia General')], default='BACKOFFICE', max_length=20),
        ),
    ]
