# Generated by Django 6.0.8 on 2026-08-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0006_empleado_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohoras',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrohoras',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
