# Generated by Django 6.0.8 on 2026-08-26 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0007_registrohoras_hora_entrada_registrohoras_hora_salida'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniformeDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado')], unique=True)),
                ('color', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'ordering': ['dia_semana'],
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='uniforme_asignado',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='DocumentoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='empleados/documentos/')),
                ('nombre', models.CharField(blank=True, help_text="Nombre para mostrar (ej. 'Contrato 2026'); si se deja vacío se usa el nombre del archivo", max_length=200)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='rrhh.empleado')),
            ],
            options={
                'ordering': ['-subido_en'],
            },
        ),
    ]
