# Generated by Django 6.0.8 on 2026-08-28 20:40

from django.db import migrations, models


def backfill_categoria(apps, schema_editor):
    """Los permisos ya creados antes de que existiera esta columna no tienen
    forma de saber su categoría más que el texto libre que RRHH escribió en
    `motivo` — se infiere una sola vez aquí (mismo criterio que ya usaba el
    reporte de asistencia). De ahí en adelante la categoría la fija la
    pestaña que crea el permiso (Permisos vs. Vacaciones), no un adivinado."""
    PermisoEmpleado = apps.get_model("rrhh", "PermisoEmpleado")
    for p in PermisoEmpleado.objects.all():
        motivo = (p.motivo or "").lower()
        if "vacac" in motivo:
            p.categoria = "VACACIONES"
        elif "enferm" in motivo:
            p.categoria = "ENFERMEDAD"
        else:
            continue  # ya quedó en OTRO por el default
        p.save(update_fields=["categoria"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0008_uniformedia_empleado_uniforme_asignado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisoempleado',
            name='categoria',
            field=models.CharField(choices=[('VACACIONES', 'Vacaciones'), ('ENFERMEDAD', 'Incapacidad / enfermedad'), ('OTRO', 'Otro')], default='OTRO', max_length=12),
        ),
        migrations.RunPython(backfill_categoria, noop),
    ]
