# Generated by Django 6.0.8 on 2026-08-28 21:14

from django.db import migrations, models

# Nombres en texto libre que RRHH ya venía escribiendo en `color` (ej.
# "Azul Navi", que no es un color CSS válido) -> un hex razonable para que
# el swatch no aparezca en blanco la primera vez que se abre la pestaña.
MAPA_COLORES = [
    ("gris", "#6b7280"), ("blanco", "#f8fafc"), ("negro", "#111827"),
    ("navi", "#1e3a8a"), ("azul", "#2563eb"), ("celeste", "#38bdf8"),
    ("rojo", "#dc2626"), ("verde", "#16a34a"), ("amarillo", "#eab308"),
    ("naranja", "#f97316"), ("morado", "#7c3aed"), ("rosado", "#ec4899"),
    ("rosa", "#ec4899"), ("café", "#78350f"), ("cafe", "#78350f"),
    ("beige", "#e7d8c3"),
]


def backfill_color_hex(apps, schema_editor):
    UniformeDia = apps.get_model("rrhh", "UniformeDia")
    for d in UniformeDia.objects.exclude(color=""):
        texto = d.color.lower()
        for palabra, hexval in MAPA_COLORES:
            if palabra in texto:
                d.color_hex = hexval
                d.save(update_fields=["color_hex"])
                break


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0009_permiso_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniformedia',
            name='color_hex',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.RunPython(backfill_color_hex, noop),
    ]
