# Generated by Django 6.0.8 on 2026-09-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0010_uniforme_color_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='tipo_vinculacion',
            field=models.CharField(choices=[('FIJO', 'Trabajador fijo'), ('PASANTIA', 'Pasantía'), ('PRUEBA', 'Mes de prueba')], default='FIJO', max_length=10),
        ),
    ]
