# Generated by Django 6.0.8 on 2026-09-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0011_empleado_tipo_vinculacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisoempleado',
            name='tipo',
            field=models.CharField(choices=[('FIJO', 'Fijo (se repite cada semana)'), ('MOMENTANEO', 'Momentáneo (con fecha de inicio y fin)'), ('POR_HORA', 'Por horas (un solo día)')], max_length=12),
        ),
    ]
