# Generated by Django 6.0.8 on 2026-08-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='asesor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='fecha_factura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='monto_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='referencia_ots',
            field=models.CharField(blank=True, max_length=30, verbose_name='N.º de OT de referencia'),
        ),
    ]
