# Generated by Django 6.0.8 on 2026-08-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaproducto',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='tipo',
            field=models.CharField(choices=[('PRODUCTO', 'Producto'), ('REPUESTO', 'Repuesto'), ('INSUMO', 'Insumo'), ('ACCESORIO', 'Accesorio'), ('OTRO', 'Otro')], default='PRODUCTO', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='detalles',
            field=models.TextField(blank=True, help_text='Especificaciones técnicas, características adicionales'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
