# Generated by Django 6.0.8 on 2026-08-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_marca_producto_moneda_producto_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='asignacion',
            field=models.CharField(blank=True, help_text='Persona o área a la que está asignado', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='condicion',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('USADO', 'Usado'), ('MAL_ESTADO', 'Mal estado')], default='NUEVO', max_length=15),
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='nivel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='no_serie',
            field=models.CharField(blank=True, max_length=100, verbose_name='N.º de serie'),
        ),
        migrations.AddField(
            model_name='producto',
            name='prestado_a',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Estante o mueble donde está guardado', max_length=100),
        ),
    ]
