# Generated by Django 6.0.8 on 2026-08-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_seed_unidades_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproducto',
            name='vendible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='categoriaproducto',
            name='tipo',
            field=models.CharField(choices=[('REPUESTO', 'Repuesto'), ('INSUMO', 'Insumo'), ('EQUIPO', 'Equipo'), ('HERRAMIENTA', 'Herramienta'), ('PRODUCTO', 'Producto'), ('ACCESORIO', 'Accesorio'), ('OTRO', 'Otro')], default='PRODUCTO', max_length=20),
        ),
    ]
