# Generated by Django 6.0.8 on 2026-09-07 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_categoriaproducto_vendible_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BajaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('origen', models.CharField(blank=True, help_text='De dónde salió (ubicación o área de origen)', max_length=150)),
                ('area_destino', models.CharField(blank=True, help_text='A qué área o departamento va', max_length=150)),
                ('entregado_a', models.CharField(blank=True, help_text='Persona o entidad a la que la empresa se lo entregó', max_length=150)),
                ('motivo', models.TextField(blank=True)),
                ('dado_de_baja_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bajas_registradas', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bajas', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Baja de producto',
                'verbose_name_plural': 'Bajas de producto',
                'ordering': ['-fecha'],
            },
        ),
    ]
