# Generated by Django 6.0.8 on 2026-09-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_bajaproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajaproducto',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
