# Generated by Django 6.0.8 on 2026-08-28 22:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_cotizacion_detallecotizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppto_numero', models.CharField(blank=True, max_length=60, verbose_name='No. de PPTO')),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('cliente_nombre', models.CharField(max_length=200)),
                ('equipo_marca', models.CharField(blank=True, max_length=200)),
                ('servicio_producto', models.CharField(blank=True, max_length=255)),
                ('tipo_trabajo', models.CharField(blank=True, max_length=200)),
                ('periodo', models.CharField(blank=True, max_length=50)),
                ('fecha', models.DateField()),
                ('contacto_nombre', models.CharField(blank=True, max_length=200)),
                ('contacto_puesto', models.CharField(blank=True, max_length=200)),
                ('contacto_telefono', models.CharField(blank=True, max_length=60)),
                ('contacto_email', models.CharField(blank=True, max_length=200)),
                ('ruc', models.CharField(blank=True, max_length=60)),
                ('tipo_cambio', models.DecimalField(decimal_places=2, default=Decimal('36.63'), max_digits=8)),
                ('nota_garantia', models.CharField(blank=True, max_length=500)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemCotizacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('costo_proveedor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.cotizacioncliente')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
