# Generated by Django 6.0.8 on 2026-09-01 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_cotizacion_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecotizacion',
            name='cotizacion',
        ),
        migrations.RemoveField(
            model_name='detallecotizacion',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Cotizacion',
        ),
        migrations.DeleteModel(
            name='DetalleCotizacion',
        ),
    ]
