# Generated by Django 6.0.8 on 2026-08-05 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('TALLER', 'Taller'), ('VENTAS', 'Ventas'), ('RRHH', 'Recursos Humanos'), ('BACKOFFICE', 'Backoffice / Contabilidad'), ('ADMIN', 'Gerencia General')], default='BACKOFFICE', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
