# Generated by Django 6.0.8 on 2026-08-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='idioma',
            field=models.CharField(choices=[('es', 'Español (Latinoamérica)'), ('en', 'English (US)'), ('zh', '中文 (普通话)'), ('fr', 'Français')], default='es', max_length=5),
        ),
        migrations.AddField(
            model_name='perfil',
            name='modulos_permitidos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
