# Generated by Django 6.0.8 on 2026-08-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfil_idioma_perfil_modulos_permitidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tema',
            field=models.CharField(choices=[('auto', 'Automático (según el sistema)'), ('claro', 'Claro'), ('oscuro', 'Oscuro'), ('medianoche', 'Medianoche'), ('esmeralda', 'Esmeralda'), ('ambar', 'Ámbar')], default='auto', max_length=15),
        ),
    ]
