# Generated by Django 6.0.8 on 2026-08-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfil_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='impresora_ancho_papel',
            field=models.PositiveSmallIntegerField(choices=[(58, '58 mm'), (80, '80 mm')], default=80),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='impresora_conexion',
            field=models.CharField(blank=True, choices=[('WIN32', 'Impresora instalada en Windows'), ('RED', 'Red (IP y puerto, ESC/POS directo)')], max_length=10),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='impresora_ip',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='impresora_nombre',
            field=models.CharField(blank=True, help_text='Nombre exacto de la impresora instalada en Windows', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='impresora_puerto',
            field=models.PositiveIntegerField(default=9100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('TALLER', 'Taller'), ('PASANTE', 'Pasante de taller'), ('VENTAS', 'Ventas'), ('RRHH', 'Recursos Humanos'), ('BACKOFFICE', 'Backoffice / Contabilidad'), ('ADMIN', 'Gerencia General')], default='BACKOFFICE', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tema',
            field=models.CharField(choices=[('auto', 'Automático (según el sistema)'), ('claro', 'Claro'), ('oscuro', 'Oscuro'), ('medianoche', 'Medianoche'), ('esmeralda', 'Esmeralda'), ('ambar', 'Ámbar'), ('blanco', 'Blanco y negro')], default='auto', max_length=15),
        ),
    ]
