# Generated by Django 6.0.8 on 2026-08-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_configuracion_impresora_ancho_papel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='eliminacion_solicitada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('TALLER', 'Taller'), ('PASANTE', 'Pasante de taller'), ('VENTAS', 'Ventas'), ('RRHH', 'Recursos Humanos'), ('BACKOFFICE', 'Backoffice / Contabilidad'), ('JEFE_OPERACIONES', 'Jefe de Operaciones'), ('ADMIN', 'Gerencia General')], default='BACKOFFICE', max_length=20),
        ),
    ]
