# Generated by Django 6.0.8 on 2026-08-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_perfil_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='siguiente_numero_cca',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='siguiente_numero_com',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
