# Generated by Django 6.0.8 on 2026-09-08 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_configuracion_siguiente_numero_cca_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(blank=True, max_length=200)),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('CREAR', 'Creación'), ('EDITAR', 'Edición'), ('ELIMINAR', 'Eliminación')], max_length=10)),
                ('metodo', models.CharField(max_length=10)),
                ('ruta', models.CharField(max_length=255)),
                ('modulo', models.CharField(blank=True, max_length=50)),
                ('resumen', models.CharField(blank=True, max_length=255)),
                ('codigo_estado', models.PositiveSmallIntegerField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de actividad',
                'verbose_name_plural': 'Registros de actividad',
                'ordering': ['-creado_en'],
            },
        ),
    ]
