from django.urls import path
from .views import (
    VentasPeriodoView,
    VentasPorVendedorView,
    CategoriasVendidasView,
    GastosInsumosView,
    GastosPersonalView,
    GastosProveedorView,
    GastosDiaView,
    EstadoResultadosView,
    InventarioMovimientoView,
    CuentasPorCobrarReporteView,
    ClientesEmpresasView,
    TallerEficienciaView,
    ExportarVentasPeriodoView,
    ExportarVentasPeriodoPdfView,
    ExportarVentasVendedoresView,
    ExportarVentasVendedoresPdfView,
    ExportarGastosView,
    ExportarGastosPdfView,
    ExportarGastosProveedorView,
    ExportarGastosProveedorPdfView,
    ExportarInventarioMovimientoView,
    ExportarInventarioMovimientoPdfView,
    ExportarCuentasPorCobrarView,
    ExportarCuentasPorCobrarPdfView,
    ExportarTallerEficienciaView,
    ExportarTallerEficienciaPdfView,
)

urlpatterns = [
    path("ventas-periodo/", VentasPeriodoView.as_view()),
    path("ventas-vendedores/", VentasPorVendedorView.as_view()),
    path("categorias-vendidas/", CategoriasVendidasView.as_view()),
    path("gastos-insumos/", GastosInsumosView.as_view()),
    path("gastos-personal/", GastosPersonalView.as_view()),
    path("gastos-proveedor/", GastosProveedorView.as_view()),
    path("gastos-dia/", GastosDiaView.as_view()),
    path("estado-resultados/", EstadoResultadosView.as_view()),
    path("inventario-movimiento/", InventarioMovimientoView.as_view()),
    path("cuentas-por-cobrar/", CuentasPorCobrarReporteView.as_view()),
    path("clientes-empresas/", ClientesEmpresasView.as_view()),
    path("taller-eficiencia/", TallerEficienciaView.as_view()),
    path("ventas-periodo/exportar/", ExportarVentasPeriodoView.as_view()),
    path("ventas-periodo/exportar-pdf/", ExportarVentasPeriodoPdfView.as_view()),
    path("ventas-vendedores/exportar/", ExportarVentasVendedoresView.as_view()),
    path("ventas-vendedores/exportar-pdf/", ExportarVentasVendedoresPdfView.as_view()),
    path("gastos/exportar/", ExportarGastosView.as_view()),
    path("gastos/exportar-pdf/", ExportarGastosPdfView.as_view()),
    path("gastos-proveedor/exportar/", ExportarGastosProveedorView.as_view()),
    path("gastos-proveedor/exportar-pdf/", ExportarGastosProveedorPdfView.as_view()),
    path("inventario-movimiento/exportar/", ExportarInventarioMovimientoView.as_view()),
    path("inventario-movimiento/exportar-pdf/", ExportarInventarioMovimientoPdfView.as_view()),
    path("cuentas-por-cobrar/exportar/", ExportarCuentasPorCobrarView.as_view()),
    path("cuentas-por-cobrar/exportar-pdf/", ExportarCuentasPorCobrarPdfView.as_view()),
    path("taller-eficiencia/exportar/", ExportarTallerEficienciaView.as_view()),
    path("taller-eficiencia/exportar-pdf/", ExportarTallerEficienciaPdfView.as_view()),
]
